name: Publish Docker image

env:
  #TENANT_ID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
  SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
  SP_CLIENT_SECRET:  ${{ secrets.SP_CLIENT_SECRET }}
  ARC_LOGIN_NAME: "mytestregistryuis"
  CONTAINER_REGISTRY_NAME: "mytestregistryuis.azurecr.io"

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

jobs:
  job1:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate
        run: |
          az login --username $SP_CLIENT_ID --password $SP_CLIENT_SECRET
          az acr login --name $ARC_LOGIN_NAME

      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Build container image
        run: |
          CONTAINER_NAME="accessitportalfrontend:${GITHUB_SHA::8}"
          echo "Building container image: $CONTAINER_NAME"
          docker build --pull --rm --tag $CONTAINER_NAME "."
          docker tag $CONTAINER_NAME $CONTAINER_REGISTRY_NAME/$CONTAINER_NAME

      - name: Push container image to ACR
        run: |
          CONTAINER_NAME="accessitportalfrontend:${GITHUB_SHA::8}"
          echo "Push container image: $CONTAINER_NAME"
          docker push $CONTAINER_REGISTRY_NAME/$CONTAINER_NAME & wait